import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../../../globals.css";
import React from "react";
import Routes from "@/components/routeHandler";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>{children}</>
   
  );
}
